kind: Template
apiVersion: v1
metadata:
  annotations:
    description: Sonarqube
    tags: sonarqube
  name: sonarqube-persistent
objects:
- kind: ServiceAccount
  apiVersion: v1
  metadata:
    creationTimestamp: null
    labels:
      app: ${APPLICATION_NAME}
    name: ${APPLICATION_NAME}
- kind: Service
  apiVersion: v1
  metadata:
    annotations:
      description: Sonarqube
    labels:
      app: ${APPLICATION_NAME}
    name: ${APPLICATION_NAME}
  spec:
    ports:
    - name: 9000-tcp
      port: 9000
      protocol: TCP
      targetPort: 9000
    selector:
      app: ${APPLICATION_NAME}
      deploymentconfig: ${APPLICATION_NAME}
    sessionAffinity: None
    type: ClusterIP
  status:
    loadBalancer: {}
- kind: Route
  apiVersion: v1
  id: ${APPLICATION_NAME}-http
  metadata:
    annotations:
      description: Route for application's http service.
    labels:
      app: ${APPLICATION_NAME}
    name: ${APPLICATION_NAME}
  spec:
    host: ${HOSTNAME}
    to:
      name: ${APPLICATION_NAME}
- kind: DeploymentConfig
  apiVersion: v1
  metadata:
    labels:
      app: ${APPLICATION_NAME}
    name: ${APPLICATION_NAME}
  spec:
    replicas: 1
    selector:
      app: ${APPLICATION_NAME}
      deploymentconfig: ${APPLICATION_NAME}
    strategy:
      resources: {}
      type: Recreate
      recreateParams:
        timeoutSeconds: 600   
    template:
      metadata:
        creationTimestamp: null
        labels:
          app: ${APPLICATION_NAME}
          deploymentconfig: ${APPLICATION_NAME}
      spec:
        serviceAccountName: ${APPLICATION_NAME}
        containers:
        - env:
          - name: SONARQUBE_JDBC_USERNAME
            value: ${SONARQUBE_JDBC_USERNAME}
          - name: SONARQUBE_JDBC_PASSWORD
            value: ${SONARQUBE_JDBC_PASSWORD}
          - name: SONARQUBE_JDBC_URL
            value: jdbc:postgresql://postgresql/${SONARQUBE_JDBC_DBNAME}
        - image: " "
          imagePullPolicy: Always
          name: ${APPLICATION_NAME}
          ports:
          - containerPort: 9000
            protocol: TCP
          resources:
            limits:
              cpu: '2'
              memory: 2Gi
            requests:
              cpu: '1'
              memory: 1Gi
          terminationMessagePath: /dev/termination-log
          volumeMounts:
          - name: sonarqube-data
            mountPath: /opt/sonarqube/data
          readinessProbe:
              httpGet:
                path: /about
                port: 9000
                scheme: HTTP
              initialDelaySeconds: 20
              timeoutSeconds: 1
              periodSeconds: 10
              successThreshold: 1
              failureThreshold: 3
          livenessProbe:
              exec:
                command:
                  - echo
                  - ok
              initialDelaySeconds: 40
              timeoutSeconds: 1
              periodSeconds: 10
              successThreshold: 1
              failureThreshold: 3
        dnsPolicy: ClusterFirst
        restartPolicy: Always
        securityContext: {}
        terminationGracePeriodSeconds: 30
        volumes:
        - name: sonarqube-data
          persistentVolumeClaim:
            claimName: sonarqube-pvc
    test: false
    triggers:
    - type: ConfigChange
    - imageChangeParams:
        automatic: true
        containerNames:
        - ${APPLICATION_NAME}
        from:
          kind: ImageStreamTag
          name: ${APPLICATION_NAME}:${SONARQUBE_VERSION}
      type: ImageChange
- kind: ImageStream
  apiVersion: v1
  metadata:
    labels:
      app: ${APPLICATION_NAME}
    name: ${APPLICATION_NAME}
  spec:
    tags:
    - name: "${SONARQUBE_VERSION}"
      from:
        kind: DockerImage
        name: wkulhanek/${APPLICATION_NAME}:${SONARQUBE_VERSION}
      importPolicy: {}
      annotations:
        description: Sonarqube docker image
        tags: sonarqube
        version: "${SONARQUBE_VERSION}"
- kind: PersistentVolumeClaim
  apiVersion: v1
  metadata:
    name: sonarqube-pvc
    labels:
      app: ${APPLICATION_NAME}
  spec:
    accessModes:
      - ReadWriteOnce
    resources:
      requests:
        storage: ${SONARQUBE_VOLUME_CAPACITY}
parameters:
- description: The name for the application.
  name: APPLICATION_NAME
  required: true
  value: sonarqube
- description: 'Custom hostname for http service route.  Leave blank for default hostname, e.g.: <application-name>-<project>.<default-domain-suffix>'
  name: HOSTNAME
  required: true
- description: Volume space available for data, e.g. 512Mi, 2Gi
  name: SONARQUBE_VOLUME_CAPACITY
  required: false
  value: 4Gi
- description: Sonarqube version
  name: SONARQUBE_VERSION
  required: false
  value: 6.7.3
- description: Sonarqube JDBC username
  name: SONARQUBE_JDBC_USERNAME
  required: false
  value: sonar
- description: Sonarqube JDBC password
  name: SONARQUBE_JDBC_PASSWORD
  required: false
  value: sonar
- description: Sonarqube DB name
  name: SONARQUBE_JDBC_DBNAME
  required: false
  value: sonar
